site_name: Aide-mémoire Nimble
site_description: Résumé condensé et vérifié des règles du système de jeu de rôle Nimble
site_author: Fred Ben
repo_name: dolmenwood-nimble
repo_url: https://github.com/fredben78/dolmenwood-nimble

nav:
  - Accueil: index.md
  - Aide-mémoire: fondamentaux-nimble.md
  - Mentions légales: NOTICE.md

theme:
  name: material
  language: fr
  palette:
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Basculer en mode clair
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode sombre
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji

plugins:
  - search:
      lang: fr
